{{- if .Values.autoscaler.enabled }}
{{- if eq .Release.Namespace "jx-production" }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "gorush.fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "gorush.fullname" . }}
  minReplicas: {{ .Values.autoscaler.minReplicas }}
  maxReplicas: {{ .Values.autoscaler.maxReplicas }}
{{- if .Values.autoscaler.targetCpuAverageUtilization }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.autoscaler.targetCpuAverageUtilization }}
{{- end }}
{{- end }}
{{- end }}
