{{ $need_volumes := false }}
{{- range .Values.secrets -}}
{{- if .plain }}
{{- if .plain.file }}
{{ $need_volumes = true }}
{{- end}}
{{- else if .keyVal }}
{{- $from := .from  }}
{{- range .keyVal }}
{{ if .file }}
{{ $need_volumes = true }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "gorush.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
{{- if .Values.deploymentStrategy }}
  strategy:
{{ toYaml .Values.deploymentStrategy | indent 4 }}
{{- end }}
  template:
    metadata:
      labels:
        app: {{ include "gorush.fullname" . }}
{{- range $lkey, $lval := .Values.globalLabels }}
        {{ $lkey }}: {{ $lval }}
{{- end }}
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
{{- range $pkey, $pval := .Values.env }}
        - name: {{ $pkey }}
          value: {{ $pval }}
{{- end }}
{{ if hasKey .Values "secrets" }}
        envFrom:
        - secretRef:
            name: {{ include "gorush.fullname" . }}-env
{{ end }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- end }}
{{- if .Values.livenessProbe }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: {{ .Values.service.internalPort }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
{{- end }}
{{- if .Values.readinessProbe }}
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.path }}
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
{{- end }}
{{- if $need_volumes }}
        volumeMounts:
{{- range .Values.secrets -}}
{{- if .plain }}
{{- if .plain.file }}
        - name: {{ .from }}
          mountPath: {{ .plain.file }}
          subPath: {{ base .plain.file }}
          readOnly: true
{{- end}}
{{- else if .keyVal }}
{{- $from := .from  }}
{{- range .keyVal }}
{{ if .file }}
        - name: {{ $from }}-{{ .key }}
          mountPath: {{ .file }}
          subPath: {{ base .file }}
          readOnly: true
{{- end }}
{{- end }}
{{- end }}
{{- end }}
      volumes:
{{- range .Values.secrets -}}
{{- if .plain }}
{{- if .plain.file }}
      - name: {{ .from }}
        secret:
          secretName: {{ with $ }}{{ include "gorush.fullname" . }}-files{{ end }}
          items:
          - key: {{ .from }}
            path: {{ base .plain.file }}
{{- end}}
{{- else if .keyVal }}
{{- $from := .from  }}
{{- range .keyVal }}
{{ if .file }}
      - name: {{ $from }}-{{ .key }}
        secret:
          secretName: {{ with $ }}{{ include "gorush.fullname" . }}-files{{ end }}
          items:
          - key: {{ $from }}-{{ .key }}
            path: {{ base .file }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
