{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "gorush.fullname" . }}
  labels:
    release: prometheus
spec:
  endpoints:
  - interval: {{ .Values.serviceMonitor.interval }}
    path: {{ .Values.serviceMonitor.endpoint }}
    port: {{ .Values.service.portName }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchNames:
    - {{ .Values.service.name }}
{{- end}}
