name: Preview

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  preview:
    uses: anghami/pipelines/.github/workflows/preview.yaml@main
    secrets: inherit
    with:
      run-tests: false
